### ISSUE TITLE
Test LDO Transfer via Wormhole to multisig held account

### ISSUE THREAD

**Issue by malikankit** [ChorusOne/solido#327]
**After** : Multisig on testnet is deployed

1. Create a can-receive-LDO account on Solana testnet blockchain
2. Make Testnet Multisig the owner of this account

3. Transfer LDO from Ethereum Blockchain to this account on Solana testnet blockchain

**After** : #320

4. Test #320 with this LDO held by the multisig account

**Comment by glottologist** [comment]
@joe-bowman Who can I pester to get access to our testnet Wormhole?

**Comment by glottologist** [comment]
So this isn't progressing so well.  I have managed to get some TESTLDO tokens but moving them through wormhole is proving problematic. 

https://www.wormholebridge.com/  doesn't work currently, I suspect due to upgrades happening. 

And both Dariusz and I have tried and failed to get the test harness to run consistently for Wormhole due to multiple issues with the build.

**Comment by ruuda** [comment]
@joe-bowman knows how to do this

**Comment by ruuda** [comment]
This has been tested and even executed on mainnet, the first round of LDO distribution is complete.
