### ISSUE TITLE
[Anchor] ClaimRewards + SendRewards

### ISSUE THREAD

**Issue by enriquefynn** [ChorusOne/solido#445]
Main issue: #438
Following the [anchor-integration](https://github.com/ChorusOne/solido/tree/anchor-integration) branch.

## ClaimRewards
stSOL rewards should be claimed, this will sell stSOL to TerraUSD on Orca (as decided in #438). Once the rewards were sold, they have to be transferred to the Terra chain by using Wormhole.
We can restrict the function to be called only in the beginning of every epoch by anyone.

@RishiSid can update on this issue once done with the Wormhole tests.

**Comment by ruuda** [comment]
I also did a transfer back from Solana to Terra of the wrapped UST:

* https://explorer.solana.com/tx/5tSRA1CYLd51sjf7Dd2ZRkLspcqiR8NH51oTd3K34sNc3PZG9uF7euE2AHE95KurrcfKYf2sCQqsEbSRmzQq8oDg?cluster=devnet

The instruction is different this time, it’s a `transfer_wrapped`, not `transfer_native`, because UST is a wrapped token on Solana.
